server:
  port: 8080

spring:
  jackson:
    date-format: org.openapitools.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

document:
  service:
    base-url: http://localhost:8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.boot.web.reactive.error: DEBUG
